project_id = "bfhdtmxmlcfyxjgracbz"

[functions.get-stock-prices]
verify_jwt = false

[functions.get-news]
verify_jwt = false

[functions.get-earnings]
verify_jwt = false

[functions.get-stock-fundamentals]
verify_jwt = false

[functions.update-top-100]
verify_jwt = false

[functions.update-stock-prices]
verify_jwt = false

[functions.ai-stock-advisor]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
